### ISSUE TITLE
SARIF "kind" not handled

### ISSUE THREAD

**Issue by candrews** [fortify/fortify-ssc-parser-sarif#18]
SARIF's [kind](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317647) is not currently handled. `kind` is how SARIF records findings for tests that were done or skipped or errored out as well as vulnerabilities (`kind`=`fail`, the default if `kind` is absent, indicates a vulnerability).

The values for `kind` and what I think this plugin should do in each case are:
* `pass` should not record the vulnerability in fortify
* `open` should behave the same as `fail`
* `informational` should not record the vulnerability in fortify
* `notApplicable` should not record the vulnerability in fortify
* `review` should behave the same as `fail`
* `fail` (default is `kind` is no specified) should record the vulnerability in fortify (the current behavior)

**Comment by rsenden** [comment]
Thanks for raising this. This is potentially a breaking change as it may change what data gets imported into SSC. Any chance you can submit a PR for this?

**Comment by candrews** [comment]
> This is potentially a breaking change as it may change what data gets imported into SSC.

Agreed, it _could_ be breaking. FWIW, none of the example files use SARIF `kind`.

> Any chance you can submit a PR for this?

Here you go: https://github.com/fortify/fortify-ssc-parser-sarif/pull/19

**Comment by rsenden** [comment]
My attempts to release this as a breaking change failed (trying to change `feat:` to `feat!:` based on [these instructions](https://github.com/googleapis/release-please#how-can-i-fix-release-notes)). Not a big issue as this will likely hardly affect any current users, so released as v1.5.0 now.
